Добавляет главную страницу
htmlacademy-htmlcss/244435-device-33 pull request #2
Opened 2022-02-02 19:52 UTC by RukiiaBagaudin

2022-02-03 11:58 UTC, VanillaWulf commented on index.html
> +  <main class="main-index">
в мейне должны быть секции

2022-02-03 11:58 UTC, VanillaWulf commented on index.html
> +      <img class="slider-image" src="" alt="Белый квадрокоптер" />
img не обязательно закрывать />

2022-02-03 11:58 UTC, VanillaWulf commented on index.html
> +      <button class="slider-button slider-prev">
тайп

2022-02-03 14:53 UTC, RukiiaBagaudin commented on index.html
> +  <main class="main-index">
Они же вроде внутри все. Не поняла, что имеется в виду, можно подробнее? Там еще у меня вопрос по слайдеру, он же ведь не секция или как?

2022-02-08 18:02 UTC, andreysgra requested changes

2022-02-08 18:02 UTC, andreysgra commented on index.html
> +    <img src="" alt="Логотип магазина Девайс" class="main-footer-logo" />
Это логотип-ссылка на главную страницу.

2022-02-09 13:54 UTC, RukiiaBagaudin commented on index.html
> +    </div>
@andreysgra Вопрос: в верхнем слайдере каждый слайд вывела в отдельный div, а внутри разделила слайд (class="slider-item") на два блока: обертку для изображения ("slider-image-wrapper") и обертку для текста("slider-details-wrapper")? Нужно ли делать так или это избыточно?

2022-02-09 17:55 UTC, merged